def error(self, i):
    print("error")
