def error(self, i):
    print("error")
    raise ValueError("error")
