def error(i):
  print("error")